### ISSUE TITLE
all-higher-set can be simplified

### ISSUE THREAD

**Issue by falk-hueffner** [WojciechMula/toys#12]
in bit-twiddling/all-higher-set.c, the function can be simplified:

```
int is_pattern(uint16_t x) {
    const uint16_t n = -x;
    return (n ^ x) < x;
}
```

**Comment by WojciechMula** [comment]
Thanks a lot! Will update soon. :)

**Comment by WojciechMula** [comment]
Finally added. That's really clever, like it very much.
