### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by morrisonlevi** [WojciechMula/toys#15]
I may want to use snippets from hex encoding in another project, but I need to know license information to know if it's compatible with that project's license.

**Comment by WojciechMula** [comment]
The repository contains LICENSE file, it's the BSD 2-Clause license. Clearly you overlooked it. If BSD is too restrictive for you, just drop me a line, we will work it out.

**Comment by morrisonlevi** [comment]
I overlooked this somehow. Sorry for the noise!
